version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  build-and-test:
    executor: python-executor
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover tests

workflows:
  version: 2
  build:
    jobs:
      - build-and-test

